import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/shared/NavBar";
import Footer from "@/components/shared/Footer";
import PlanProvider from "./context/PlanContext";
import { ToastContainer } from "react-toastify";



const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
<html
  lang="en"
  className={`${oswald.variable} h-full antialiased`}
>
      <body className="min-h-full flex flex-col">
      <PlanProvider>
       <NavBar/>
        <div>
        
        {children}</div>
        <Footer/>
       </PlanProvider> 
       <ToastContainer/>
       </body>
    </html>
  );
}
